config/routes.rb
require 'authenticated_user'

Rails.application.routes.draw do

  resources :product_configurations

  resources :properties, except: [:new, :create, :destroy]

  resources :financial_releases

  resources :cards, except: [:index, :destroy]

  resources :variations

  get 'loan/search_employee'

  resources :products

  get 'file/margin_file'

  resources :public_employees

  resources :attendance_locals

  resources :consignees

  resources :return_codes

  resources :organs

  resources :operators

  resources :holidays

  resources :loan

  resources :assistance

  resources :variations

  resources :negotiations
  resources :insertion_lines



  resources :users

  match '/default_password' => 'public_employees#default_password', as: 'default_password', via: [:get]

  match '/set_default_password' => 'public_employees#set_default_password', as: 'set_default_password', via: [:post]

  # Autenticacao
  post 'authenticate', to: 'session#login_attempt', as: 'authenticate'
  # Relatorios
  match '/relatorio_analitico' => 'reports#analytical', as: 'analytical_report', via: [:get]
  match '/download_analitico_servidor' => 'reports#analytical_employee', via: [:post]
  match '/download_analitico_periodo' => 'reports#analytical_period', via: [:post]
  match '/relatorio_sintetico' => 'reports#synthetic', as: 'synthetic_report', via: [:get]
  # Servidores
  match '/public_employee/:id/atualizar_contatos' => 'public_employees#update_contacts', as: 'update_contacts', via: [:patch, :post]
  match '/public_employee/:id/editar_contatos' => 'public_employees#edit_contacts', as: 'edit_contacts', via: [:get]
  match '/gerar_senha_aprovacao_servidor' => 'public_employees#generate_approval_password', as: 'generate_approval_password', via: [:post]
  match '/criar_usuario_servidor' => 'users#new_employee_user', as: 'new_employee_user', via: [:get]
  match '/create_usuario_servidor' => 'users#create_employee_user', as: 'create_employee_user', via: [:post]
  # Comum
  match '/login' => 'session#login', as: 'login', via: [:get]
  match '/sair' => 'session#logout', as: 'logout', via:[:delete]

  #match '/atualizar_senha' => 'users#change_password', as: 'change_password', via: [:get]
  #match '/trocar_senha' => 'users#update_password', as: 'update_password', via: [:post]

  match '/user/:id/alterar_senha' => 'users#change_password', as: 'change_password', via: [:get]
  match '/user/:id/trocar_senha' => 'users#update_password', as: 'update_password', via: [:patch]

  match '/inicio' => 'users#dashboard', as: 'dashboard', via: [:get]
  match '/informe_email' => 'password_resets#inform_email', as: 'reset_password_inform_email', via: [:get]
  match '/resetar_senha/:id' => 'password_resets#reset', as: 'reset', via: [:patch]
  match '/enviar_instrucoes_resetar_senha' => 'password_resets#send_reset_password_instruction', as: 'send_reset_password_instruction', via: [:post]
  match '/informe_nova_senha' => 'password_resets#inform_new_password', as: 'inform_new_password', via: [:get]
  # Usuario
  match '/bloquear_usuario' => 'users#block', as: 'block_user', via: [:get]
  match '/desbloquear_usuario' => 'users#unlock', as: 'unlock_user', via: [:get]
  match '/cadastro_servidor' => 'public_employees#manual', as: 'public_employee_manual', via: [:get]
  match '/atualizar_dados_pessoais' => 'users#change_personal_data', as: 'change_personal_data', via: [:get]
  match '/update_personal_data' => 'users#update_personal_data', as: 'update_personal_data', via: [:patch]
  match '/informe_login_password' => 'users#inform_login_and_password', as: 'inform_login_and_password', via: [:get]
  match '/update_login_for_employee_user/:token' => 'users#update_login_for_employee_user', as: 'update_login_for_employee_user', via: [:patch]
  # Arquivos
  match '/arquivo_margem' => 'file#margin_file', as: 'margin_file', via: [:get]
  match '/arquivo_retorno' => 'file#return_file', as: 'return_file', via: [:get]
  match '/upload_margem' => 'file#upload_margin_file', as: 'upload_margin_file', via: [:post]
  match '/upload_retorno' => 'file#upload_return_file', as: 'upload_return_file', via: [:post]
  match '/insercao' => 'insertion#insertion', as: 'insertion', via: [:get]
  match '/insercao_download' => 'insertion#download', as: 'insertion_download', via: [:get]
  match '/generate_insertion_file' => 'insertion#generate_file', as: 'generate_insertion_file', via: [:post]
  match '/retorno_consignataria' => 'insertion_lines#download_file', as: 'download_file', via: [:get]
  # Consulta
  match '/consultar_servidor' => 'search_form#search_employee', as: 'search_employee', via: [:get]
  match '/consultar' => 'search_form#search', as: 'search', via: [:post]
  # Contrato
  match '/gerenciar_contrato' => 'loan#manage_loan', as: 'manage_loan', via: [:get]
  match '/loan/:id/liquidar_contrato' => 'loan#liquidate', as: 'liquidate_loan', via: [:get]
  match '/loan/:id/executar_liquidacao_contrato' => 'loan#liquidate_execute', as: 'liquidate_execute_loan', via: [:patch]
  match '/loan/:id/suspender_contrato' => 'loan#suspended', as: 'suspend_loan', via: [:get]
  match '/loan/:id/executar_suspensao_contrato' => 'loan#suspended_execute', as: 'suspend_execute_loan', via: [:patch]
  match '/loan/:id/recusar_contrato' => 'loan#refuse', as: 'refuse_loan', via:[:get]
  match '/loan/:id/recusar_contrato_executar' => 'loan#refuse_execute', as: 'refuse_loan_execute', via: [:patch]
  match '/loan/:id/aprovar_contrato' => 'loan#approve', as: 'loan_approve', via: [:get]
  match '/loan/:id/executar_aprovacao_contrato' => 'loan#approve_execute', as: 'approve_execute_loan', via: [:patch]
  match '/loan/:id/cancelar_contrato' => 'loan#cancel', as: 'loan_cancel', via: [:get]
  match '/loan/id/emprestimos_portabilidade' => 'loan#loans_portability', as: 'loans_portability', via: [:get]
  match '/loan/:id/executar_cancelamento' => 'loan#cancel_execute', as: 'cancel_execute_loan', via: [:patch]
  match '/busca_contratos_portabilidade' => 'loan#search_for_portability', as: 'search_for_portability', via: [:get]
  match '/busca_servidor' => 'public_employees#search_for_operation', as: 'search_for_operation', via: [:get]
  match '/solicitar_portabilidade' => 'loan#request_portability', as: 'request_portability', via: [:post]
  match '/gerenciar_portabilidade' => 'portability_requests#manage_requests', as: 'manage_portability', via: [:get]
  match '/portability_request/:id/responder_requisicao' => 'portability_requests#answer_request', as: 'answer_request', via: [:get]
  match '/portability_request/:id/responder_requisicao_executar' => 'portability_requests#answer_request_execute', as: 'answer_request_execute', via: [:patch]
  match '/loan/:id/:request_id/:operation_type/novo_refinanciamento' => 'loan#new_refin', as: 'new_refin', via: [:get]
  match '/loan/:id/:request_id/:operation_type/criar_refinanciamento' => 'loan#create_refin', as: 'create_refin', via: [:post]
  match '/loan/:id/:request_id/nova_portabilidade' => 'loan#new_portability', as: 'new_portability', via: [:get]
  match '/loan/:id/:request_id/efetuar_porabilidade' => 'loan#create_portability', as: 'create_portability', via: [:post]
  # Contrato Assistencial
  match '/contratos_assistenciais' => 'assistance#manage_assistance_contract', as: 'manage_assistance_contract', via: [:get]
  match '/assistance/:id/aprovar_contrato_assistencial' => 'assistance#approve', as: 'assistance_approve', via: [:get]
  match '/assistance/:id/executar_aprovacao_assistencial' => 'assistance#approve_execute', as: 'approve_execute_assistance', via: [:patch]
  match '/assistance/:id/recusar_assistencial' => 'assistance#refuse', as: 'assistance_refuse', via: [:get]
  match '/assistance/:id/executar_reprovacao_assistencial' => 'assistance#refuse_execute', as: 'refuse_execute_assistance', via: [:patch]
  match '/assistance/:id/suspender_assistencial' => 'assistance#suspended', as: 'suspended_assistance', via: [:get]
  match '/assistance/:id/suspender_assistencial_executar' => 'assistance#suspended_execute', as:'suspended_assistance_execute', via: [:patch]
  match '/assistance/:id/cancelar_contracto' => 'assistance#cancel', as: 'cancel_assistance', via: [:get]
  match '/assistance/:id/executar_cancelamento' => 'assistance#cancel_execute', as: 'cancel_assistance_execute', via: [:patch]
  # Cartão
  match '/cartoes' => 'cards#manage_cards', as: 'manage_cards', via: [:get]
  match '/card/:id/aprovar_cartao' => 'cards#approve', as: 'card_approve', via: [:get]
  match '/card/:id/executar_aprovacao' => 'cards#approve_execute', as: 'approve_execute', via: [:patch]
  match '/card/:id/recusar_cartao' => 'cards#refuse', as: 'card_refuse', via: [:get]
  match '/card/:id/executar_reprovacao' => 'cards#refuse_execute', as: 'refuse_execute', via: [:patch]
  match '/card/:id/cancelar_cartao' => 'cards#cancel', as: 'card_cancel', via: [:get]
  match '/card/:id/executar_cancelamento' => 'cards#cancel_execute', as: 'cancel_execute', via: [:patch]
  match '/arquivo_lancamentos' => 'financial_releases#file_release', as: 'file_release', via: [:get]
  match '/upload_lancamentos'=> 'financial_releases#upload', as: 'upload_releases', via: [:post]

  match '/public_employee/:id/tranferir_servidor' => 'public_employees#transfer_employee', as: 'transfer_employee', via: [:get]
  match '/public_employee/:id/executar_transferencia' => 'public_employees#execute_transference', as: 'execute_transference', via: [:patch, :post]

  match '/product_configuration/:id/ativar' => 'product_configurations#active', as: 'active_configuration', via: [:post]
  match '/product_configuration/:id/desativar' => 'product_configurations#disable', as: 'disable_configuration', via: [:post]


  root :to => 'users#dashboard', constraints: AuthenticatedUser

  root :to => 'session#login', as: 'guest_root'
end

app/helpers/assistance_helper.rb
module AssistanceHelper
end

app/views/assistance/_assistance_grid.html.erb
<%= grid(@assistance_grid) do |g|

  g.column name: 'Consignatária' do |assistance|
    assistance.consignee.name if assistance.consignee
  end

  g.column name: 'Valor do desconto' do |assistance|
    format_currency(assistance.discount_value)
  end

end -%>

app/views/assistance/_assistance_information.html.erb
<div class="row">
  <div class="col-lg-12">
    <section class="panel">
      <header class="panel-heading">
        <h2 class="panel-title"><%= 'Dados do contrato' %></h2>
      </header>
      <div class="panel-body">
        <div class="col-lg-3">
          <p>
            <b><%= 'Número do contrato' %>:</b>
            <%= @assistance.contract_number %>
          </p>
          <p>
            <b><%= 'Servidor' %>:</b>
            <%= @assistance.public_employee.name %>
          </p>
          <p>
            <b><%= 'CPF' %>:</b>
            <%= @assistance.public_employee.cpf %>
          </p>
        </div>
        <div class="col-lg-3">
          <p>
            <b><%= 'Mátricula' %>:</b>
            <%= @assistance.public_employee.registration %>
          </p>
          <p>
            <b><%= 'Valor do contrato' %>:</b>
            <%= format_currency(@assistance.discount_value) %>
          </p>
          <p>
            <b><%= 'Status' %>:</b>
            <%= @assistance.status %>
          </p>
        </div>
        <div class="col-lg-3">
          <p>
            <b><%= 'Data' %>:</b>
            <%= @assistance.created_at.strftime('%d/%m/%Y') %>
          </p>
        </div>
      </div>
    </section>
  </div>
</div>

app/views/assistance/_employee_information.html.erb
<section class="panel">
  <header class="panel-heading">
    <h2 class="panel-title"><%= 'Dados do servidor' %></h2>
  </header>
  <div class="panel-body">
    <div class="col-lg-12">
      <div class="row">
        <div class="col-sm-4">
          <div class="form-group">
            <%= label_tag 'Nome', nil ,class: 'control-label' %>
            <%= text_field_tag 'name', @employee.name, class: 'form-control', :readonly => true  %>
          </div>
        </div>
        <div class="col-sm-4">
          <div class="form-group">
            <%= label_tag 'CPF', nil ,class: 'control-label' %>
            <%= text_field_tag 'cpf', @employee.cpf, class: 'form-control', :readonly => true  %>
          </div>
        </div>
        <div class="col-sm-4">
          <div class="form-group">
            <%= label_tag 'Data Admissão', nil ,class: 'control-label' %>
            <%= text_field_tag 'admission_date', @employee.admission_date.strftime('%d/%m/%Y'), class: 'form-control', :readonly => true  %>
          </div>
        </div>
      </div>

      <div class="row">
        <div class="col-sm-4">
          <div class="form-group">
            <%= label_tag 'Matricula', nil ,class: 'control-label' %>
            <%= text_field_tag 'admission_date', @employee.registration, class: 'form-control', :readonly => true  %>
          </div>
        </div>
        <div class="col-sm-4">
          <div class="form-group">
            <%= label_tag 'Órgão', nil ,class: 'control-label' %>
            <%= text_field_tag 'organ', @employee.organ.name, class: 'form-control', :readonly => true  %>
          </div>
        </div>
        <div class="col-sm-4">
          <div class="form-group">
            <%= label_tag 'Tipo Contratação', nil ,class: 'control-label' %>
            <%= text_field_tag 'commissioned', @employee.commissioned.name, class: 'form-control', :readonly => true  %>
          </div>
        </div>
      </div>

      <div class="row">
        <div class="col-sm-4">
          <div class="form-group">
            <%= label_tag 'Cargo', nil ,class: 'control-label' %>
            <%= text_field_tag 'role', @employee.role, class: 'form-control', :readonly => true  %>
          </div>
        </div>
        <div class="col-sm-4">
          <div class="form-group">
            <%= label_tag 'Marem', nil ,class: 'control-label' %>
            <%= text_field_tag 'margin_value', format_currency(@employee.margin_value) , class: 'form-control', :readonly => true  %>
          </div>
        </div>
        <div class="col-sm-4">
          <div class="form-group">
            <%= label_tag 'Margem Disponivel', nil ,class: 'control-label' %>
            <%= text_field_tag 'margin_available', format_currency(@employee.assistance_margin_available), class: 'form-control', :readonly => true  %>
          </div>
        </div>
      </div>

    </div>

  </div>
</section>

app/views/assistance/_form.html.erb
<%= form_for @assistance, :url => url_for(:controller => 'assistance', :action => @action), :html => {:class => 'form-horizontal form-bordered'} do |f| %>
    <div class="row">
        <div class="col-lg-12">
            <section class="panel">
                <header class="panel-heading">
                  <h2 class="panel-title"><%= 'Dados de contrato assistencial' %></h2>
                </header>
                <div class="panel-body">
                  <div class="form-group">
                    <%= f.label :discount_value, class: 'col-md-3 control-label asterisk' %>
                    <div class="col-md-6">
                      <%= f.text_field :discount_value, class: 'form-control money', :required => true, :readonly => f.object.persisted? %>
                      <%= "<span class='help-block-error'>#{@assistance.errors[:discount_value].first}</span>".html_safe if @assistance.errors[:discount_value].first %>
                    </div>
                  </div>
                  <div class="form-group">
                    <%= f.label :approval_password, class: 'col-md-3 control-label' %>
                    <div class="col-md-6">
                      <%= f.password_field :approval_password, class: 'form-control' %>
                      <%= "<span class='help-block-error'>#{@assistance.errors[:approval_password].first}</span>".html_safe if @assistance.errors[:approval_password].first %>
                    </div>
                  </div>
                </div>
            </section>
          <div class="actions">
            <%= f.submit :class => 'btn btn-primary' %>
            <%= link_to I18n.t('organ.back'), search_employee_path, class: 'btn btn-warning' %>
          </div>
        </div>
    </div>

<% end %>

app/views/assistance/_manage_assistance_grid.html.erb
<%= grid(@manage_assistance_grid, show_filters: :when_filtered) do |g|

  g.blank_slate do
    content_tag :div, 'Nenhum Contrato Assistencial encontrado.', class: 'well'
  end

  g.column name: 'Número contrato' do |assistance|
    assistance.contract_number if assistance.contract_number
  end

  g.column name: 'Nome' do |assistance|
    assistance.public_employee.name
  end

  g.column name: 'Matricula', attribute: 'registration', model: 'PublicEmployee', auto_reload: true do |assistance|
    assistance.public_employee.registration
  end

  g.column name: 'Data operação' do |assistance|
    assistance.created_at.strftime("%d/%m/%Y")
  end

  g.column name: 'Status' do |assistance|
    assistance.status
  end

  g.column do |assistance|

    buffer = link_to assistance_path(assistance) do
        '<i class="fa fa-lg fa-search" title="Exibir"></i>'.html_safe
    end

    if assistance.status == AssistanceContract::AGUARDANDO_SERVIDOR
      buffer += '   '
      buffer += link_to edit_assistance_path(assistance) do
        '<i class="fa fa-lg fa-edit" title="Editar"></i>'.html_safe
      end

    end

    if assistance.status == AssistanceContract::AGUARDANDO_SERVIDOR || assistance.status == AssistanceContract::AUTORIZADO_SERVIDOR
      buffer += '   '
      buffer += link_to cancel_assistance_path(assistance) do
        '<i class="fa fa-lg fa-minus-circle" title="Cancelar Reserva"></i>'.html_safe
      end
    end

    if assistance.status == AssistanceContract::AUTORIZADO_SERVIDOR
      if can? :approve, :assistance
        buffer += '   '
        buffer += link_to assistance_approve_path(assistance) do
          '<i class="fa fa-lg fa-check" title="Aprovar"></i>'.html_safe
        end
      end
      if can? :refuse, :assistance
        buffer += '   '
        buffer += link_to assistance_refuse_path(assistance) do
          '<i class="fa fa-lg fa-remove" title="Recusar"></i>'.html_safe
        end
      end
    end
    if assistance.status == AssistanceContract::EM_FOLHA
      buffer += '   '
        buffer += link_to suspended_assistance_path(assistance) do
            '<i class="fa fa-lg fa-ban" title="Suspender"></i>'.html_safe
        end
    end
    if can? :index, :variation
      if assistance.status == AssistanceContract::EM_FOLHA || assistance.status == AssistanceContract::APROVADO
        buffer += '   '
        buffer += link_to variations_path(:assistance_id => assistance.id) do
          '<i class="fa fa-lg fa-plus" title="Variação"></i>'.html_safe
        end
      end
    end

    raw buffer
  end

end -%>

app/views/assistance/approve.html.erb
<header class="page-header">
  <h2><%= 'Aprovar Assistencial' %></h2>

  <div class="right-wrapper pull-right">
    <a class="sidebar-right-toggle" data-open="sidebar-right"><i class="fa fa-chevron-left"></i></a>
  </div>
</header>
<%= render :partial => 'assistance/assistance_information', :locals => {:assistance => @assistance} %>

<div class="row">
  <div class="col-lg-12">
    <%= form_for @assistance, url: approve_execute_assistance_path, :html => {:class => 'form-horizontal form-bordered'} do |f| %>
        <section class="panel">
            <div class="panel-body">
              <%= f.hidden_field :operator_id, :value => current_user.operator.id %>
              <div class="form-group">
                <%= f.label :contract_number, class: 'col-md-3 control-label asterisk' %>
                <div class="col-md-6">
                  <%= f.text_field :contract_number, class: 'form-control', :placeholder => 'Ex: 0.000.000,00' %>
                  <%= "<span class='help-block-error'>#{@assistance.errors[:contract_number].first}</span>".html_safe if @assistance.errors[:contract_number].first %>
                </div>
              </div>
              <div class="form-group">
                <%= f.label :observation, class: 'col-md-3 control-label' %>
                <div class="col-md-6">
                  <%= f.text_area :observation, class: 'form-control' %>
                </div>
              </div>
            </div>
        </section>
        <div class="actions">
          <%= submit_tag 'Aprovar', :class => "btn btn-primary" %>
          <%= link_to I18n.t('reusable.back'), manage_assistance_contract_path, class: 'btn btn-warning' %>
        </div>
    <% end %>
  </div>
</div>

app/views/assistance/cancel.html.erb
<header class="page-header">
  <h2><%= 'Cancelar Reserva' %></h2>

  <div class="right-wrapper pull-right">
    <a class="sidebar-right-toggle" data-open="sidebar-right"><i class="fa fa-chevron-left"></i></a>
  </div>
</header>
<%= render :partial => 'assistance/assistance_information', :locals => {:assistance => @assistance} %>

<div class="row">
  <div class="col-lg-12">
    <%= form_for @assistance, url: cancel_assistance_execute_path, :html => {:class => 'form-horizontal form-bordered'} do |f| %>
        <section class="panel">
          <div class="panel-body">
            <%= f.hidden_field :operator_id, :value => current_user.operator.id %>
            <div class="form-group">
              <%= f.label :observation, class: 'col-md-3 control-label asterisk' %>
              <div class="col-md-6">
                <%= f.text_area :observation, class: 'form-control' %>
                <%= "<span class='help-block-error'>#{@assistance.errors[:observation].first}</span>".html_safe if @assistance.errors[:observation].first %>
              </div>
            </div>
            <div class="form-group">
              <%= f.label :password, class: 'col-md-3 control-label asterisk' %>
              <div class="col-md-6">
                <%= f.password_field :password, class: 'form-control' %>
                <%= "<span class='help-block-error'>#{@assistance.errors[:password].first}</span>".html_safe if @assistance.errors[:password].first %>
              </div>
            </div>
          </div>
        </section>
        <div class="actions">
          <%= f.submit 'Cancelar Reserva', :class => "btn btn-primary" %>
          <%= link_to I18n.t('reusable.back'), manage_assistance_contract_path, class: 'btn btn-warning' %>
        </div>
    <% end %>
  </div>
</div>

app/views/assistance/edit.html.erb
<header class="page-header">
  <h2><%= 'Editar Assistencial' %></h2>

  <div class="right-wrapper pull-right">
    <a class="sidebar-right-toggle" data-open="sidebar-right"><i class="fa fa-chevron-left"></i></a>
  </div>
</header>
<%= render 'assistance/employee_information' %>

<br>

<%= render 'assistance/form' %>

app/views/assistance/manage_assistance_contract.html.erb
<header class="page-header">
  <h2><%= 'Gerenciar Contratos Assistenciais' %></h2>

  <div class="right-wrapper pull-right">
    <a class="sidebar-right-toggle" data-open="sidebar-right"><i class="fa fa-chevron-left"></i></a>
  </div>
</header>
<div class="row">
    <div class="col-lg-12">
        <section class="panel">
            <div class="panel-body">
              <%= render partial: 'manage_assistance_grid' %>
            </div>
        </section>
    </div>
</div>

app/views/assistance/new.html.erb
<header class="page-header">
  <h2><%= 'Novo Contrato Assistencial' %></h2>

  <div class="right-wrapper pull-right">
    <a class="sidebar-right-toggle" data-open="sidebar-right"><i class="fa fa-chevron-left"></i></a>
  </div>
</header>

<%= render 'assistance/employee_information' %>

<br>

<%= render 'assistance/form' %>

app/views/assistance/refuse.html.erb
<header class="page-header">
  <h2><%= 'Recusar Assistencial' %></h2>

  <div class="right-wrapper pull-right">
    <a class="sidebar-right-toggle" data-open="sidebar-right"><i class="fa fa-chevron-left"></i></a>
  </div>
</header>

<%= render :partial => 'assistance/assistance_information', :locals => {:assistance => @assistance} %>

<div class="row">
  <div class="col-lg-12">
    <%= form_for @assistance, url: refuse_execute_assistance_path, :html => {:class => 'form-horizontal form-bordered'} do |f| %>
        <section class="panel">
          <div class="panel-body">
            <%= f.hidden_field :operator_id, :value => current_user.operator.id %>
            <div class="form-group">
              <%= f.label :observation, class: 'col-md-3 control-label asterisk' %>
              <div class="col-md-6">
                <%= f.text_area :observation, class: 'form-control' %>
                <%= "<span class='help-block-error'>#{@assistance.errors[:observation].first}</span>".html_safe if @assistance.errors[:observation].first %>
              </div>
            </div>
          </div>
        </section>
        <div class="actions">
          <%= submit_tag 'Recusar', :class => "btn btn-primary" %>
          <%= link_to I18n.t('reusable.back'), manage_assistance_contract_path, class: 'btn btn-warning' %>
        </div>
    <% end %>
  </div>
</div>

app/views/assistance/show.html.erb
<header class="page-header">
  <h2><%= 'Exibir Assistencial' %></h2>

  <div class="right-wrapper pull-right">
    <a class="sidebar-right-toggle" data-open="sidebar-right"><i class="fa fa-chevron-left"></i></a>
  </div>
</header>
<div class="row">
  <div class="col-lg-12">
    <section class="panel">
      <header class="panel-heading">
        <h2 class="panel-title"><%= 'Dados do servidor' %></h2>
      </header>
      <div class="panel-body">
        <div class="col-lg-4">
          <p>
            <b><%= 'Servidor' %>:</b>
            <%= @assistance.public_employee.name if @assistance.public_employee %>
          </p>
          <p>
            <b><%= 'CPF' %>:</b>
            <%= @assistance.public_employee.format_cpf if @assistance.public_employee %>
          </p>
          <p>
            <b><%= 'Mátricula' %>:</b>
            <%= @assistance.public_employee.registration if @assistance.public_employee %>
          </p>
          <p>
            <b><%= 'Órgão' %>:</b>
            <%= @assistance.public_employee.organ.name if @assistance.public_employee && @assistance.public_employee.organ %>
          </p>
        </div>
      </div>
    </section>
  </div>
</div>

<div class="row">
  <div class="col-lg-12">
    <section class="panel">
      <header class="panel-heading">
        <h2 class="panel-title"><%= 'Dados do contrato assistencial' %></h2>
      </header>
      <div class="panel-body">
        <div class="col-lg-4">
          <p>
            <b><%= 'Valor do desconto' %>:</b>
            <%= format_currency(@assistance.discount_value) %>
          </p>
          <p>
            <b><%= 'Status' %>:</b>
            <%= @assistance.status %>
          </p>
          <p>
            <b><%= 'Consignatária' %>:</b>
            <%= @assistance.consignee.name if @assistance.consignee %>
          </p>
          <p>
            <b><%= 'Data' %>:</b>
            <%= @assistance.created_at.strftime('%d/%m/%Y') %>
          </p>
        </div>
      </div>
    </section>
  </div>
</div>

<div class="actions">
  <%= link_to I18n.t('reusable.back'), manage_assistance_contract_path, class: 'btn btn-warning' %>
</div>

app/views/assistance/suspended.html.erb
<header class="page-header">
  <h2><%= 'Suspender Assistencial' %></h2>

  <div class="right-wrapper pull-right">
    <a class="sidebar-right-toggle" data-open="sidebar-right"><i class="fa fa-chevron-left"></i></a>
  </div>
</header>

<%= render :partial => 'assistance/assistance_information', :locals => {:assistance => @assistance} %>

<div class="row">
  <div class="col-lg-12">
    <%= form_for @assistance, url: suspended_assistance_execute_path, :html => {:class => 'form-horizontal form-bordered'} do |f| %>
        <section class="panel">
          <div class="panel-body">
            <%= f.hidden_field :operator_id, :value => current_user.operator.id %>
            <div class="form-group">
              <%= f.label :observation, class: 'col-md-3 control-label asterisk' %>
              <div class="col-md-6">
                <%= f.text_area :observation, class: 'form-control' %>
                <%= "<span class='help-block-error'>#{@assistance.errors[:observation].first}</span>".html_safe if @assistance.errors[:observation].first %>
              </div>
            </div>
          </div>
        </section>
        <div class="actions">
          <%= submit_tag 'Suspender', :class => "btn btn-primary" %>
          <%= link_to I18n.t('reusable.back'), manage_assistance_contract_path, class: 'btn btn-warning' %>
        </div>
    <% end %>
  </div>
</div>