config/routes.rb
require 'authenticated_user'

Rails.application.routes.draw do

  resources :product_configurations

  resources :properties, except: [:new, :create, :destroy]

  resources :financial_releases

  resources :cards, except: [:index, :destroy]

  resources :variations

  get 'loan/search_employee'

  resources :products

  get 'file/margin_file'

  resources :public_employees

  resources :attendance_locals

  resources :consignees

  resources :return_codes

  resources :organs

  resources :operators

  resources :holidays

  resources :loan

  resources :assistance

  resources :variations

  resources :negotiations
  resources :insertion_lines



  resources :users

  match '/default_password' => 'public_employees#default_password', as: 'default_password', via: [:get]

  match '/set_default_password' => 'public_employees#set_default_password', as: 'set_default_password', via: [:post]

  # Autenticacao
  post 'authenticate', to: 'session#login_attempt', as: 'authenticate'
  # Relatorios
  match '/relatorio_analitico' => 'reports#analytical', as: 'analytical_report', via: [:get]
  match '/download_analitico_servidor' => 'reports#analytical_employee', via: [:post]
  match '/download_analitico_periodo' => 'reports#analytical_period', via: [:post]
  match '/relatorio_sintetico' => 'reports#synthetic', as: 'synthetic_report', via: [:get]
  # Servidores
  match '/public_employee/:id/atualizar_contatos' => 'public_employees#update_contacts', as: 'update_contacts', via: [:patch, :post]
  match '/public_employee/:id/editar_contatos' => 'public_employees#edit_contacts', as: 'edit_contacts', via: [:get]
  match '/gerar_senha_aprovacao_servidor' => 'public_employees#generate_approval_password', as: 'generate_approval_password', via: [:post]
  match '/criar_usuario_servidor' => 'users#new_employee_user', as: 'new_employee_user', via: [:get]
  match '/create_usuario_servidor' => 'users#create_employee_user', as: 'create_employee_user', via: [:post]
  # Comum
  match '/login' => 'session#login', as: 'login', via: [:get]
  match '/sair' => 'session#logout', as: 'logout', via:[:delete]

  #match '/atualizar_senha' => 'users#change_password', as: 'change_password', via: [:get]
  #match '/trocar_senha' => 'users#update_password', as: 'update_password', via: [:post]

  match '/user/:id/alterar_senha' => 'users#change_password', as: 'change_password', via: [:get]
  match '/user/:id/trocar_senha' => 'users#update_password', as: 'update_password', via: [:patch]

  match '/inicio' => 'users#dashboard', as: 'dashboard', via: [:get]
  match '/informe_email' => 'password_resets#inform_email', as: 'reset_password_inform_email', via: [:get]
  match '/resetar_senha/:id' => 'password_resets#reset', as: 'reset', via: [:patch]
  match '/enviar_instrucoes_resetar_senha' => 'password_resets#send_reset_password_instruction', as: 'send_reset_password_instruction', via: [:post]
  match '/informe_nova_senha' => 'password_resets#inform_new_password', as: 'inform_new_password', via: [:get]
  # Usuario
  match '/bloquear_usuario' => 'users#block', as: 'block_user', via: [:get]
  match '/desbloquear_usuario' => 'users#unlock', as: 'unlock_user', via: [:get]
  match '/cadastro_servidor' => 'public_employees#manual', as: 'public_employee_manual', via: [:get]
  match '/atualizar_dados_pessoais' => 'users#change_personal_data', as: 'change_personal_data', via: [:get]
  match '/update_personal_data' => 'users#update_personal_data', as: 'update_personal_data', via: [:patch]
  match '/informe_login_password' => 'users#inform_login_and_password', as: 'inform_login_and_password', via: [:get]
  match '/update_login_for_employee_user/:token' => 'users#update_login_for_employee_user', as: 'update_login_for_employee_user', via: [:patch]
  # Arquivos
  match '/arquivo_margem' => 'file#margin_file', as: 'margin_file', via: [:get]
  match '/arquivo_retorno' => 'file#return_file', as: 'return_file', via: [:get]
  match '/upload_margem' => 'file#upload_margin_file', as: 'upload_margin_file', via: [:post]
  match '/upload_retorno' => 'file#upload_return_file', as: 'upload_return_file', via: [:post]
  match '/insercao' => 'insertion#insertion', as: 'insertion', via: [:get]
  match '/insercao_download' => 'insertion#download', as: 'insertion_download', via: [:get]
  match '/generate_insertion_file' => 'insertion#generate_file', as: 'generate_insertion_file', via: [:post]
  match '/retorno_consignataria' => 'insertion_lines#download_file', as: 'download_file', via: [:get]
  # Consulta
  match '/consultar_servidor' => 'search_form#search_employee', as: 'search_employee', via: [:get]
  match '/consultar' => 'search_form#search', as: 'search', via: [:post]
  # Contrato
  match '/gerenciar_contrato' => 'loan#manage_loan', as: 'manage_loan', via: [:get]
  match '/loan/:id/liquidar_contrato' => 'loan#liquidate', as: 'liquidate_loan', via: [:get]
  match '/loan/:id/executar_liquidacao_contrato' => 'loan#liquidate_execute', as: 'liquidate_execute_loan', via: [:patch]
  match '/loan/:id/suspender_contrato' => 'loan#suspended', as: 'suspend_loan', via: [:get]
  match '/loan/:id/executar_suspensao_contrato' => 'loan#suspended_execute', as: 'suspend_execute_loan', via: [:patch]
  match '/loan/:id/recusar_contrato' => 'loan#refuse', as: 'refuse_loan', via:[:get]
  match '/loan/:id/recusar_contrato_executar' => 'loan#refuse_execute', as: 'refuse_loan_execute', via: [:patch]
  match '/loan/:id/aprovar_contrato' => 'loan#approve', as: 'loan_approve', via: [:get]
  match '/loan/:id/executar_aprovacao_contrato' => 'loan#approve_execute', as: 'approve_execute_loan', via: [:patch]
  match '/loan/:id/cancelar_contrato' => 'loan#cancel', as: 'loan_cancel', via: [:get]
  match '/loan/id/emprestimos_portabilidade' => 'loan#loans_portability', as: 'loans_portability', via: [:get]
  match '/loan/:id/executar_cancelamento' => 'loan#cancel_execute', as: 'cancel_execute_loan', via: [:patch]
  match '/busca_contratos_portabilidade' => 'loan#search_for_portability', as: 'search_for_portability', via: [:get]
  match '/busca_servidor' => 'public_employees#search_for_operation', as: 'search_for_operation', via: [:get]
  match '/solicitar_portabilidade' => 'loan#request_portability', as: 'request_portability', via: [:post]
  match '/gerenciar_portabilidade' => 'portability_requests#manage_requests', as: 'manage_portability', via: [:get]
  match '/portability_request/:id/responder_requisicao' => 'portability_requests#answer_request', as: 'answer_request', via: [:get]
  match '/portability_request/:id/responder_requisicao_executar' => 'portability_requests#answer_request_execute', as: 'answer_request_execute', via: [:patch]
  match '/loan/:id/:request_id/:operation_type/novo_refinanciamento' => 'loan#new_refin', as: 'new_refin', via: [:get]
  match '/loan/:id/:request_id/:operation_type/criar_refinanciamento' => 'loan#create_refin', as: 'create_refin', via: [:post]
  match '/loan/:id/:request_id/nova_portabilidade' => 'loan#new_portability', as: 'new_portability', via: [:get]
  match '/loan/:id/:request_id/efetuar_porabilidade' => 'loan#create_portability', as: 'create_portability', via: [:post]
  # Contrato Assistencial
  match '/contratos_assistenciais' => 'assistance#manage_assistance_contract', as: 'manage_assistance_contract', via: [:get]
  match '/assistance/:id/aprovar_contrato_assistencial' => 'assistance#approve', as: 'assistance_approve', via: [:get]
  match '/assistance/:id/executar_aprovacao_assistencial' => 'assistance#approve_execute', as: 'approve_execute_assistance', via: [:patch]
  match '/assistance/:id/recusar_assistencial' => 'assistance#refuse', as: 'assistance_refuse', via: [:get]
  match '/assistance/:id/executar_reprovacao_assistencial' => 'assistance#refuse_execute', as: 'refuse_execute_assistance', via: [:patch]
  match '/assistance/:id/suspender_assistencial' => 'assistance#suspended', as: 'suspended_assistance', via: [:get]
  match '/assistance/:id/suspender_assistencial_executar' => 'assistance#suspended_execute', as:'suspended_assistance_execute', via: [:patch]
  match '/assistance/:id/cancelar_contracto' => 'assistance#cancel', as: 'cancel_assistance', via: [:get]
  match '/assistance/:id/executar_cancelamento' => 'assistance#cancel_execute', as: 'cancel_assistance_execute', via: [:patch]
  # Cartão
  match '/cartoes' => 'cards#manage_cards', as: 'manage_cards', via: [:get]
  match '/card/:id/aprovar_cartao' => 'cards#approve', as: 'card_approve', via: [:get]
  match '/card/:id/executar_aprovacao' => 'cards#approve_execute', as: 'approve_execute', via: [:patch]
  match '/card/:id/recusar_cartao' => 'cards#refuse', as: 'card_refuse', via: [:get]
  match '/card/:id/executar_reprovacao' => 'cards#refuse_execute', as: 'refuse_execute', via: [:patch]
  match '/card/:id/cancelar_cartao' => 'cards#cancel', as: 'card_cancel', via: [:get]
  match '/card/:id/executar_cancelamento' => 'cards#cancel_execute', as: 'cancel_execute', via: [:patch]
  match '/arquivo_lancamentos' => 'financial_releases#file_release', as: 'file_release', via: [:get]
  match '/upload_lancamentos'=> 'financial_releases#upload', as: 'upload_releases', via: [:post]

  match '/public_employee/:id/tranferir_servidor' => 'public_employees#transfer_employee', as: 'transfer_employee', via: [:get]
  match '/public_employee/:id/executar_transferencia' => 'public_employees#execute_transference', as: 'execute_transference', via: [:patch, :post]

  match '/product_configuration/:id/ativar' => 'product_configurations#active', as: 'active_configuration', via: [:post]
  match '/product_configuration/:id/desativar' => 'product_configurations#disable', as: 'disable_configuration', via: [:post]


  root :to => 'users#dashboard', constraints: AuthenticatedUser

  root :to => 'session#login', as: 'guest_root'
end

app/models/card/as_approve_card.rb
class Card::AsApproveCard < ActiveType::Record[Card]

  attribute :observation, :text
  attribute :operator_id, :integer

  before_save :set_approved_status
  after_save :create_observation if :validate_observation


  def create_observation
    observation = CardObservation.new
    observation.text = self.observation
    observation.operator_id = self.operator_id
    observation.card = self
    observation.save!
  end

  def set_approved_status
    self.status = Card::AUTORIZADO_CONSIGNATARIA
  end

  def validate_observation
    self.observation.blank? ? false : true
  end

end

app/models/card/as_refuse_card.rb
class Card::AsRefuseCard < ActiveType::Record[Card]

  attribute :observation, :text
  attribute :operator_id, :integer

  before_save :set_status
  after_save :create_observation

  def set_status
    self.status = Card::REPROVADO_CONSIGNATARIA
  end

  def create_observation
    observation = CardObservation.new
    observation.text = self.observation
    observation.operator_id = self.operator_id
    observation.card_id = self
    observation.save!
  end

end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
  authorize_resource :class => :card_controller

  before_action :set_card, only: [:show, :edit, :update, :destroy]

  # GET /cards
  # GET /cards.json
  def index
    @cards = Card.all
  end

  # GET /cards/1
  # GET /cards/1.json
  def show
  end

  def manage_cards
    @cards = Card.where(:consignee_id => current_user.get_consignee).order('status').order('created_at ASC')

    if current_user.get_consignee
      if current_user.isS?(User::CONSIGNEE_CARD_MASTER) || current_user.isS?(User::FORMALIZATION_CARD)
        @manage_card_grid = initialize_grid(Card,
                                            :include => [:public_employee],
                                            :conditions => { :consignee_id => current_user.get_consignee },
                                            order: 'cards.created_at',
                                            order_direction: 'desc')
      else
        @manage_card_grid = initialize_grid(Card,
                                            :include => [:public_employee],
                                            :conditions => { :consignee_id => current_user.get_consignee,
                                                             :operator_id => current_user.operator.id },
                                            order: 'cards.created_at',
                                            order_direction: 'desc')
      end

    else
      @manage_card_grid = initialize_grid(Card,
                                          :include => [:public_employee],
                                          order: 'cards.created_at',
                                          order_direction: 'desc')
    end
  end

  # GET /cards/new
  def new

    if !params[:format].blank?
      session[:employee_id] = params[:format].to_i
    end

    @employee = PublicEmployee.where(:id => session[:employee_id]).first

    @card = Card.new
  end

  # GET /cards/1/edit
  def edit
    card = Card.find(params[:id])

    @employee = card.public_employee
  end

  # POST /cards
  # POST /cards.json
  def create
    @card = Card.new(card_params)
    @card.public_employee_id = session[:employee_id]
    @card.operator = current_user.operator
    @card.consignee = current_user.get_consignee

    property = Property.where(:category => Property::CARD_LIMIT).take

    if @card.public_employee.cards.where(:status => [Card::AUTORIZADO_SERVIDOR, Card::AUTORIZADO_CONSIGNATARIA]).count > property.value.to_i
      flash[:error] = 'Operação não pôde ser realizada, pois o limite de cartões para o servidor especificado foi atingido'
      redirect_to search_employee_path
    else
      respond_to do |format|
        if @card.save
          flash[:success] = 'Reserva de margem realizada com sucesso.'
          format.html { redirect_to search_employee_path }
        else
          @employee = @card.public_employee
          format.html { render :new }
        end
      end
    end
  end

  # PATCH/PUT /cards/1
  # PATCH/PUT /cards/1.json
  def update
    @card.approval_password = params[:card][:approval_password]

    if @card.valid?
      if !@card.approval_password.blank?
        @card.update_attribute(:status, Card::AUTORIZADO_SERVIDOR)
        flash[:success] = 'Cartão atualizado com sucesso.'
        redirect_to manage_cards_path
      end
    else
      @employee = @card.public_employee
      render :edit
    end

  end

  # DELETE /cards/1
  # DELETE /cards/1.json
  def destroy
    @card.destroy
    respond_to do |format|
      format.html { redirect_to cards_url, notice: 'Card was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def approve
    load_card(Card::AsApproveCard)
    build_approve_card(Card::AsApproveCard)
  end

  def approve_execute
    load_card(Card::AsApproveCard)
    build_approve_card(Card::AsApproveCard)

    ActiveRecord::Base.transaction do
      save_card or render :approve
    end
  end

  def refuse
    load_card(Card::AsRefuseCard)
    build_refuse_card(Card::AsRefuseCard)
  end

  def refuse_execute

    load_card(Card::AsRefuseCard)
    build_refuse_card(Card::AsRefuseCard)

    ActiveRecord::Base.transaction do
      save_card or render :refuse
    end

  end

  def cancel
    load_card(Card::AsCancelCard)
    build_cancel_card(Card::AsCancelCard)
  end

  def cancel_execute

    load_card(Card::AsCancelCard)
    build_cancel_card(Card::AsCancelCard)

    ActiveRecord::Base.transaction do
      save_card or render :cancel
    end

  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_card
      @card = Card.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def card_params
      params.require(:card).permit(:proposal_number, :discount_value, :approval_password)
    end

    def make_manege_card_grid
      grid = initialize_grid(Card,
                             :include => [:consignee],
                             :custom_order => {
                                 'loans.consignee_id' => 'consignees.name'
                             },
                             :conditions => ["public_employee_id = ? and status in (?)", @employee.id, [Loan::APROVADO, Loan::EM_FOLHA]])
    end

    def validate_approval_password(password, employee)

    end

    def load_card(scope)
      if @card.class == Card
        @card = nil
      end
      @card ||= card_scope(scope).find(params[:id])
    end

    def build_approve_card(scope)
      @card ||= card_scope(scope).build
      @card.attributes = approve_card_params
    end

    def build_refuse_card(scope)
      @card ||= card_scope(scope).build
      @card.attributes = refuse_card_params
    end

    def build_cancel_card(scope)
      @card ||= card_scope(scope).build
      @card.attributes = cancel_card_params
    end

    def save_card
      if @card.save

        card = params[:card][:action]

        case card
          when 'approve_execute'
            flash[:success] = 'Cartão Aprovado com sucesso.'
          when 'refuse_execute'
            flash[:success] = 'Cartão Reprovado com sucesso'
          else
            flash[:success] = 'Operação efetuada com sucesso'
        end

        redirect_to manage_cards_path
      end
    end

    def card_scope(scope)
      scope.where(nil)
    end

    def approve_card_params
      approve_card_params = params[:card]
      approve_card_params ? approve_card_params.permit(:proposal_number, :observation, :operator_id) : {}
    end

    def refuse_card_params
      refuse_card_params = params[:card]
      refuse_card_params ? refuse_card_params.permit(:observation, :operator_id) : {}
    end

    def cancel_card_params
      cancel_card_params = params[:card]
      cancel_card_params ? cancel_card_params.permit(:observation, :operator_id, :password) : {}
    end

end

app/helpers/cards_helper.rb
module CardsHelper
end

app/views/cards/_card_information.html.erb
<div class="row">
  <div class="col-lg-12">
    <section class="panel">
      <header class="panel-heading">
        <h2 class="panel-title"><%= 'Dados da proposta' %></h2>
      </header>
      <div class="panel-body">
        <div class="col-lg-3">
          <p>
            <b><%= 'Número proposta:' %></b>
            <%= card.proposal_number %>
          </p>
          <p>
            <b><%= 'Servidor:' %></b>
            <%= card.public_employee.name %>
          </p>
          <p>
            <b><%= 'CPF:' %></b>
            <%= card.public_employee.cpf %>
          </p>
        </div>
        <div class="col-lg-3">
          <p>
            <b><%= 'Mátricula:' %></b>
            <%= card.public_employee.registration %>
          </p>
          <p>
            <b><%= 'Valor desconto:' %></b>
            <%= format_currency(card.discount_value) %>
          </p>
          <p>
            <b><%= 'Status:' %></b>
            <%= card.status %>
          </p>
        </div>
        <div class="col-lg-3">
          <p>
            <b><%= 'Data:' %></b>
            <%= card.created_at.strftime('%d/%m/%Y') %>
          </p>
        </div>
      </div>
    </section>
  </div>
</div>

app/views/cards/_employee_information.html.erb
<section class="panel">
  <header class="panel-heading">
    <h2 class="panel-title"><%= 'Dados do servidor' %></h2>
  </header>
  <div class="panel-body">
    <div class="col-lg-12">
      <div class="row">
        <div class="col-sm-4">
          <div class="form-group">
            <%= label_tag 'Nome', nil ,class: 'control-label' %>
            <%= text_field_tag 'name', @employee.name, class: 'form-control', :readonly => true  %>
          </div>
        </div>
        <div class="col-sm-4">
          <div class="form-group">
            <%= label_tag 'CPF', nil ,class: 'control-label' %>
            <%= text_field_tag 'cpf', @employee.cpf, class: 'form-control', :readonly => true  %>
          </div>
        </div>
        <div class="col-sm-4">
          <div class="form-group">
            <%= label_tag 'Data Admissão', nil ,class: 'control-label' %>
            <%= text_field_tag 'admission_date', @employee.admission_date.strftime('%d/%m/%Y'), class: 'form-control', :readonly => true  %>
          </div>
        </div>
      </div>

      <div class="row">
        <div class="col-sm-4">
          <div class="form-group">
            <%= label_tag 'Matricula', nil ,class: 'control-label' %>
            <%= text_field_tag 'admission_date', @employee.registration, class: 'form-control', :readonly => true  %>
          </div>
        </div>
        <div class="col-sm-4">
          <div class="form-group">
            <%= label_tag 'Órgão', nil ,class: 'control-label' %>
            <%= text_field_tag 'organ', @employee.organ.name, class: 'form-control', :readonly => true  %>
          </div>
        </div>
        <div class="col-sm-4">
          <div class="form-group">
            <%= label_tag 'Tipo Contratação', nil ,class: 'control-label' %>
            <%= text_field_tag 'commissioned', @employee.commissioned.name, class: 'form-control', :readonly => true  %>
          </div>
        </div>
      </div>

      <div class="row">
        <div class="col-sm-4">
          <div class="form-group">
            <%= label_tag 'Cargo', nil ,class: 'control-label' %>
            <%= text_field_tag 'role', @employee.role, class: 'form-control', :readonly => true  %>
          </div>
        </div>
        <div class="col-sm-4">
          <div class="form-group">
            <%= label_tag 'Marem', nil ,class: 'control-label' %>
            <%= text_field_tag 'margin_value', format_currency(@employee.margin_value) , class: 'form-control', :readonly => true  %>
          </div>
        </div>
        <div class="col-sm-4">
          <div class="form-group">
            <%= label_tag 'Margem Disponivel', nil ,class: 'control-label' %>
            <%= text_field_tag 'margin_available', format_currency(@employee.card_margin_available), class: 'form-control', :readonly => true  %>
          </div>
        </div>
      </div>

    </div>

  </div>
</section>

app/views/cards/_manage_card_grid.html.erb
<%= grid(@manage_card_grid, show_filters: :when_filtered ) do |g|

  g.blank_slate do
    content_tag :div, 'Nenhum cartão encontrado.', class: 'well'
  end

  g.column name: 'Número da proposta', attribute: 'proposal_number', auto_reload: true do |card|
    card.proposal_number
  end

  g.column name: 'Servidor', attribute: 'name', model: 'PublicEmployee', auto_reload: true do |card|
    card.public_employee.name
  end

  g.column name: 'CPF', attribute: 'cpf', model: 'PublicEmployee', auto_reload: true do |card|
    card.public_employee.cpf
  end

  g.column name: 'Mátricula', attribute: 'registration', model: 'PublicEmployee', auto_reload: true do |card|
    card.public_employee.registration
  end

  g.column name: 'Valor', attribute: 'discount_value', auto_reload: true do |card|
    format_currency(card.discount_value)
  end

  g.column name: 'Status', attribute: 'status', auto_reload: true do |card|
    card.status
  end

  g.column do |card|
    buffer = link_to card_path(card) do
        '<i class="fa fa-lg fa-search" title="Exibir"></i>'.html_safe
    end

    if card.status == Card::AGUARDANDO_SERVIDOR
      buffer += '   '
        buffer += link_to edit_card_path(card) do
            '<i class="fa fa-lg fa-edit" title="Editar"></i>'.html_safe
        end
    end
    if card.status == Card::AUTORIZADO_SERVIDOR
      if can? :approve, :card_controller
        buffer += '   '
        buffer += link_to card_approve_path(card) do
          '<i class="fa fa-lg fa-check" title="Aprovar"></i>'.html_safe
        end
      end
      if can? :refuse, :card_controller
        buffer += '   '
        buffer += link_to card_refuse_path(card) do
          '<i class="fa fa-lg fa-remove" title="Recusar"></i>'.html_safe
        end
      end
    end
    if card.status != Card::CANCELADO || card.status != Card::REPROVADO_CONSIGNATARIA
      buffer += '   '
        buffer += link_to card_cancel_path(card) do
            '<i class="fa fa-lg fa-ban" title="Cancelar"></i>'.html_safe
        end
    end
  end

end -%>

app/views/cards/approve.html.erb
<header class="page-header">
  <h2><%= 'Aprovar Cartão' %></h2>

  <div class="right-wrapper pull-right">
    <a class="sidebar-right-toggle" data-open="sidebar-right"><i class="fa fa-chevron-left"></i></a>
  </div>
</header>
<%= render :partial => 'card_information', :locals => {:card => @card} %>

<div class="row">
  <div class="col-lg-12">
    <%= form_for @card, url: approve_execute_path, :html => {:class => 'form-horizontal form-bordered'} do |f| %>
        <section class="panel">
          <div class="panel-body">
            <%= f.hidden_field :operator_id, :value => current_user.operator_id %>
            <div class="form-group">
              <%= f.label :proposal_number, class: 'col-md-3 control-label asterisk' %>
              <div class="col-md-6">
                <%= f.text_field :proposal_number, class: 'form-control' %>
                <%= "<span class='help-block-error'>#{@card.errors[:proposal_number].first}</span>".html_safe if @card.errors[:proposal_number].first %>
              </div>
            </div>
            <div class="form-group">
              <%= f.label :observation, class: 'col-md-3 control-label' %>
              <div class="col-md-6">
                <%= f.text_area :observation, class: 'form-control' %>
              </div>
            </div>
          </div>
        </section>
        <div class="actions">
          <%= submit_tag 'Aprovar', :class => "btn btn-primary" %>
          <%= link_to I18n.t('reusable.back'), manage_cards_path, class: 'btn btn-warning' %>
        </div>
    <% end %>
  </div>
</div>

app/views/cards/cancel.html.erb
<header class="page-header">
  <h2><%= 'Cancelar Cartão' %></h2>

  <div class="right-wrapper pull-right">
    <a class="sidebar-right-toggle" data-open="sidebar-right"><i class="fa fa-chevron-left"></i></a>
  </div>
</header>
  <%= render :partial => 'card_information', :locals => {:card => @card} %>

  <div class="row">
    <div class="col-lg-12">
      <%= form_for @card, url: cancel_execute_path, :html => {:class => 'form-horizontal form-bordered'} do |f| %>
        <section class="panel">
            <div class="panel-body">
              <%= f.hidden_field :operator_id, :value => current_user.operator.id %>
              <div class="form-group">
                <%= f.label :observation, class: 'col-md-3 control-label asterisk' %>
                <div class="col-md-6">
                  <%= f.text_area :observation, class: 'form-control' %>
                  <%= "<span class='help-block-error'>#{@card.errors[:observation].first}</span>".html_safe if @card.errors[:observation].first %>
                </div>
              </div>
              <div class="form-group">
                <%= f.label :password, class: 'col-md-3 control-label asterisk' %>
                <div class="col-md-6">
                  <%= f.password_field :password, class: 'form-control' %>
                  <%= "<span class='help-block-error'>#{@card.errors[:password].first}</span>".html_safe if @card.errors[:password].first %>
                </div>
              </div>
            </div>
        </section>
          <div class="actions">
            <%= submit_tag 'Cancelar', :class => "btn btn-primary" %>
            <%= link_to I18n.t('reusable.back'), manage_cards_path, class: 'btn btn-warning' %>
          </div>
      <% end %>
    </div>
  </div>

app/views/cards/index.html.erb
<div class="general-box">

  <h3><%= 'Cartões' %></h3>

  <br>
  <br>

  <%= render :partial => 'cards/grid' %>

  <br>

  <%= link_to 'New Card', new_card_path %>

</div>

app/views/cards/refuse.html.erb
<header class="page-header">
  <h2><%= 'Recusar Cartão' %></h2>

  <div class="right-wrapper pull-right">
    <a class="sidebar-right-toggle" data-open="sidebar-right"><i class="fa fa-chevron-left"></i></a>
  </div>
</header>
<%= render :partial => 'card_information', :locals => {:card => @card} %>

<div class="row">
  <div class="col-lg-12">
    <%= form_for @card, url: refuse_execute_path, :html => {:class => 'form-horizontal form-bordered'} do |f| %>
        <section class="panel">
          <div class="panel-body">
            <%= f.hidden_field :operator_id, :value => current_user.operator.id %>
            <div class="form-group">
              <%= f.label :observation, class: 'col-md-3 control-label asterisk' %>
              <div class="col-md-6">
                <%= f.text_area :observation, class: 'form-control' %>
                <%= "<span class='help-block-error'>#{@card.errors[:observation].first}</span>".html_safe if @card.errors[:observation].first %>
              </div>
            </div>
          </div>
        </section>
        <div class="actions">
          <%= submit_tag 'Recusar', :class => "btn btn-primary" %>
          <%= link_to I18n.t('reusable.back'), manage_cards_path, class: 'btn btn-warning' %>
        </div>
    <% end %>
  </div>
</div>