config/routes.rb
require 'authenticated_user'

Rails.application.routes.draw do

  resources :product_configurations

  resources :properties, except: [:new, :create, :destroy]

  resources :financial_releases

  resources :cards, except: [:index, :destroy]

  resources :variations

  get 'loan/search_employee'

  resources :products

  get 'file/margin_file'

  resources :public_employees

  resources :attendance_locals

  resources :consignees

  resources :return_codes

  resources :organs

  resources :operators

  resources :holidays

  resources :loan

  resources :assistance

  resources :variations

  resources :negotiations
  resources :insertion_lines



  resources :users

  match '/default_password' => 'public_employees#default_password', as: 'default_password', via: [:get]

  match '/set_default_password' => 'public_employees#set_default_password', as: 'set_default_password', via: [:post]

  # Autenticacao
  post 'authenticate', to: 'session#login_attempt', as: 'authenticate'
  # Relatorios
  match '/relatorio_analitico' => 'reports#analytical', as: 'analytical_report', via: [:get]
  match '/download_analitico_servidor' => 'reports#analytical_employee', via: [:post]
  match '/download_analitico_periodo' => 'reports#analytical_period', via: [:post]
  match '/relatorio_sintetico' => 'reports#synthetic', as: 'synthetic_report', via: [:get]
  # Servidores
  match '/public_employee/:id/atualizar_contatos' => 'public_employees#update_contacts', as: 'update_contacts', via: [:patch, :post]
  match '/public_employee/:id/editar_contatos' => 'public_employees#edit_contacts', as: 'edit_contacts', via: [:get]
  match '/gerar_senha_aprovacao_servidor' => 'public_employees#generate_approval_password', as: 'generate_approval_password', via: [:post]
  match '/criar_usuario_servidor' => 'users#new_employee_user', as: 'new_employee_user', via: [:get]
  match '/create_usuario_servidor' => 'users#create_employee_user', as: 'create_employee_user', via: [:post]
  # Comum
  match '/login' => 'session#login', as: 'login', via: [:get]
  match '/sair' => 'session#logout', as: 'logout', via:[:delete]

  #match '/atualizar_senha' => 'users#change_password', as: 'change_password', via: [:get]
  #match '/trocar_senha' => 'users#update_password', as: 'update_password', via: [:post]

  match '/user/:id/alterar_senha' => 'users#change_password', as: 'change_password', via: [:get]
  match '/user/:id/trocar_senha' => 'users#update_password', as: 'update_password', via: [:patch]

  match '/inicio' => 'users#dashboard', as: 'dashboard', via: [:get]
  match '/informe_email' => 'password_resets#inform_email', as: 'reset_password_inform_email', via: [:get]
  match '/resetar_senha/:id' => 'password_resets#reset', as: 'reset', via: [:patch]
  match '/enviar_instrucoes_resetar_senha' => 'password_resets#send_reset_password_instruction', as: 'send_reset_password_instruction', via: [:post]
  match '/informe_nova_senha' => 'password_resets#inform_new_password', as: 'inform_new_password', via: [:get]
  # Usuario
  match '/bloquear_usuario' => 'users#block', as: 'block_user', via: [:get]
  match '/desbloquear_usuario' => 'users#unlock', as: 'unlock_user', via: [:get]
  match '/cadastro_servidor' => 'public_employees#manual', as: 'public_employee_manual', via: [:get]
  match '/atualizar_dados_pessoais' => 'users#change_personal_data', as: 'change_personal_data', via: [:get]
  match '/update_personal_data' => 'users#update_personal_data', as: 'update_personal_data', via: [:patch]
  match '/informe_login_password' => 'users#inform_login_and_password', as: 'inform_login_and_password', via: [:get]
  match '/update_login_for_employee_user/:token' => 'users#update_login_for_employee_user', as: 'update_login_for_employee_user', via: [:patch]
  # Arquivos
  match '/arquivo_margem' => 'file#margin_file', as: 'margin_file', via: [:get]
  match '/arquivo_retorno' => 'file#return_file', as: 'return_file', via: [:get]
  match '/upload_margem' => 'file#upload_margin_file', as: 'upload_margin_file', via: [:post]
  match '/upload_retorno' => 'file#upload_return_file', as: 'upload_return_file', via: [:post]
  match '/insercao' => 'insertion#insertion', as: 'insertion', via: [:get]
  match '/insercao_download' => 'insertion#download', as: 'insertion_download', via: [:get]
  match '/generate_insertion_file' => 'insertion#generate_file', as: 'generate_insertion_file', via: [:post]
  match '/retorno_consignataria' => 'insertion_lines#download_file', as: 'download_file', via: [:get]
  # Consulta
  match '/consultar_servidor' => 'search_form#search_employee', as: 'search_employee', via: [:get]
  match '/consultar' => 'search_form#search', as: 'search', via: [:post]
  # Contrato
  match '/gerenciar_contrato' => 'loan#manage_loan', as: 'manage_loan', via: [:get]
  match '/loan/:id/liquidar_contrato' => 'loan#liquidate', as: 'liquidate_loan', via: [:get]
  match '/loan/:id/executar_liquidacao_contrato' => 'loan#liquidate_execute', as: 'liquidate_execute_loan', via: [:patch]
  match '/loan/:id/suspender_contrato' => 'loan#suspended', as: 'suspend_loan', via: [:get]
  match '/loan/:id/executar_suspensao_contrato' => 'loan#suspended_execute', as: 'suspend_execute_loan', via: [:patch]
  match '/loan/:id/recusar_contrato' => 'loan#refuse', as: 'refuse_loan', via:[:get]
  match '/loan/:id/recusar_contrato_executar' => 'loan#refuse_execute', as: 'refuse_loan_execute', via: [:patch]
  match '/loan/:id/aprovar_contrato' => 'loan#approve', as: 'loan_approve', via: [:get]
  match '/loan/:id/executar_aprovacao_contrato' => 'loan#approve_execute', as: 'approve_execute_loan', via: [:patch]
  match '/loan/:id/cancelar_contrato' => 'loan#cancel', as: 'loan_cancel', via: [:get]
  match '/loan/id/emprestimos_portabilidade' => 'loan#loans_portability', as: 'loans_portability', via: [:get]
  match '/loan/:id/executar_cancelamento' => 'loan#cancel_execute', as: 'cancel_execute_loan', via: [:patch]
  match '/busca_contratos_portabilidade' => 'loan#search_for_portability', as: 'search_for_portability', via: [:get]
  match '/busca_servidor' => 'public_employees#search_for_operation', as: 'search_for_operation', via: [:get]
  match '/solicitar_portabilidade' => 'loan#request_portability', as: 'request_portability', via: [:post]
  match '/gerenciar_portabilidade' => 'portability_requests#manage_requests', as: 'manage_portability', via: [:get]
  match '/portability_request/:id/responder_requisicao' => 'portability_requests#answer_request', as: 'answer_request', via: [:get]
  match '/portability_request/:id/responder_requisicao_executar' => 'portability_requests#answer_request_execute', as: 'answer_request_execute', via: [:patch]
  match '/loan/:id/:request_id/:operation_type/novo_refinanciamento' => 'loan#new_refin', as: 'new_refin', via: [:get]
  match '/loan/:id/:request_id/:operation_type/criar_refinanciamento' => 'loan#create_refin', as: 'create_refin', via: [:post]
  match '/loan/:id/:request_id/nova_portabilidade' => 'loan#new_portability', as: 'new_portability', via: [:get]
  match '/loan/:id/:request_id/efetuar_porabilidade' => 'loan#create_portability', as: 'create_portability', via: [:post]
  # Contrato Assistencial
  match '/contratos_assistenciais' => 'assistance#manage_assistance_contract', as: 'manage_assistance_contract', via: [:get]
  match '/assistance/:id/aprovar_contrato_assistencial' => 'assistance#approve', as: 'assistance_approve', via: [:get]
  match '/assistance/:id/executar_aprovacao_assistencial' => 'assistance#approve_execute', as: 'approve_execute_assistance', via: [:patch]
  match '/assistance/:id/recusar_assistencial' => 'assistance#refuse', as: 'assistance_refuse', via: [:get]
  match '/assistance/:id/executar_reprovacao_assistencial' => 'assistance#refuse_execute', as: 'refuse_execute_assistance', via: [:patch]
  match '/assistance/:id/suspender_assistencial' => 'assistance#suspended', as: 'suspended_assistance', via: [:get]
  match '/assistance/:id/suspender_assistencial_executar' => 'assistance#suspended_execute', as:'suspended_assistance_execute', via: [:patch]
  match '/assistance/:id/cancelar_contracto' => 'assistance#cancel', as: 'cancel_assistance', via: [:get]
  match '/assistance/:id/executar_cancelamento' => 'assistance#cancel_execute', as: 'cancel_assistance_execute', via: [:patch]
  # Cartão
  match '/cartoes' => 'cards#manage_cards', as: 'manage_cards', via: [:get]
  match '/card/:id/aprovar_cartao' => 'cards#approve', as: 'card_approve', via: [:get]
  match '/card/:id/executar_aprovacao' => 'cards#approve_execute', as: 'approve_execute', via: [:patch]
  match '/card/:id/recusar_cartao' => 'cards#refuse', as: 'card_refuse', via: [:get]
  match '/card/:id/executar_reprovacao' => 'cards#refuse_execute', as: 'refuse_execute', via: [:patch]
  match '/card/:id/cancelar_cartao' => 'cards#cancel', as: 'card_cancel', via: [:get]
  match '/card/:id/executar_cancelamento' => 'cards#cancel_execute', as: 'cancel_execute', via: [:patch]
  match '/arquivo_lancamentos' => 'financial_releases#file_release', as: 'file_release', via: [:get]
  match '/upload_lancamentos'=> 'financial_releases#upload', as: 'upload_releases', via: [:post]

  match '/public_employee/:id/tranferir_servidor' => 'public_employees#transfer_employee', as: 'transfer_employee', via: [:get]
  match '/public_employee/:id/executar_transferencia' => 'public_employees#execute_transference', as: 'execute_transference', via: [:patch, :post]

  match '/product_configuration/:id/ativar' => 'product_configurations#active', as: 'active_configuration', via: [:post]
  match '/product_configuration/:id/desativar' => 'product_configurations#disable', as: 'disable_configuration', via: [:post]


  root :to => 'users#dashboard', constraints: AuthenticatedUser

  root :to => 'session#login', as: 'guest_root'
end

app/models/loan.rb
class Loan < ActiveRecord::Base

  has_paper_trail

  has_many :negotiations
  has_many :children, :through => :negotiations

  belongs_to :consignee
  belongs_to :public_employee
  belongs_to :operator
  has_many :loan_observations, dependent: :destroy
  has_many :insertion_lines
  has_many :portability_requests

  validates :contract_value, presence: true
  validates :liquid_value, presence: true
  validates :deadline, presence: true
  validates :installment_value, presence: true
  validates :origin_operation, presence: true
  validates :approval_password, presence: true, :on => :create
  validate :validate_installment_value, :on => :create
  validate :validate_approval_password

  before_create :set_status_loan
  before_create :calculate_balance_due
  before_create :set_contract_type
  after_create :create_negotiation
  after_create :set_children_status
  after_create :set_status_portability_request
  after_create :finish_portability

  attr_accessor :approval_password, :consignee_id_portability, :purchased_loans_ids, :portability_request_id, :operation_type, :portability_balance_due


  #STATUS
  AGUARDANDO_SERVIDOR =  'Aguardando Servidor'
  AUTORIZADO_SERVIDOR = 'Autorizado servidor'
  CANCELADO = 'Cancelado'
  APROVADO = 'Aprovado Consignataria'
  REPROVADO = 'Repovado Consignataria'
  EM_FOLHA = 'Em folha'
  PORTADO = 'PORTADO'
  SUSPENSO = 'Suspenso'
  REFINANCIADO = 'Refinanciado'
  PORT_RENEG = 'Portabilidade/Renegociado'
  PAGO_SERVIDOR = 'Pago pelo servidor'
  LIQUIDADO = 'Liquidado'
  AGUARDANDO_PORTABLIDADE = 'Aguardando Portabilidade'
  PORTABILIDADE_CONFIRMADA = 'Portabilidade Confirmada'
  SERVIDOR_FALECIDO = 'Servidor Falecido'

  #TIPO_CONTRATO
  NOVO = 'Novo'
  REFIN = 'Refin'
  PORT = 'Portabilidade'

  def validate_installment_value
    if !self.installment_value.blank?
      if self.installment_value > self.public_employee.loan_margin_available
        errors.add(:installment_value, 'maior do que margem disponivel')
      end
    end
  end

  def validate_approval_password

    if !approval_password.blank?
      if !self.public_employee.validate_approval_password(approval_password)
        errors.add(:approval_password, 'incorreta')
      end
    end

  end

  def set_status_loan
    if !self.approval_password.blank? && self.public_employee.validate_approval_password(self.approval_password)
      config = ProductConfiguration.joins(:product, :configuration).where('products.consignee_id = ? and configurations.category = ?', self.operator.get_consignee.id, Configuration::LOAN).first
      if config && config.value == true
        self.status = Loan::APROVADO
      else
        self.status = Loan::AUTORIZADO_SERVIDOR
      end
    else
      self.status = Loan::AGUARDANDO_SERVIDOR
    end
  end

  def calculate_balance_due
    self.balance_due = self.deadline * self.installment_value
  end

  def set_children_status
    if !self.children.empty? && self.public_employee.validate_approval_password(self.approval_password)
      self.children.each do |child|
        if self.contract_type == Loan::REFIN
          child.update_attribute(:status, Loan::REFINANCIADO)
        else
          child.update_attribute(:status, Loan::PORTADO)
        end
      end
    end
  end

  def set_contract_type
    case self.origin_operation
      when 'NEW'
        self.contract_type = Loan::NOVO
      when 'REFIN'
        self.contract_type = Loan::REFIN
      when 'PORT'
        self.contract_type = Loan::PORT
    end
  end

  def create_negotiation
    if !self.purchased_loans_ids.blank?
      self.purchased_loans_ids.each do |id|
        negotiation = Negotiation.new
        negotiation.loan = self
        negotiation.child_id = id
        self.contract_type == Loan::PORT ? negotiation.status = Negotiation::OPEN : negotiation.status = Negotiation::CLOSED
        negotiation.negotiation_type = self.contract_type
        negotiation.save!
      end
    end
  end

  def set_status_portability_request
    if self.origin_operation == 'REFIN' && self.operation_type == 'RETAIN'
      request = PortabilityRequest.find(self.portability_request_id)
      request.update_attribute(:status, PortabilityRequest::RETIDO)
    end
    if self.origin_operation == 'PORT'
      request = PortabilityRequest.find(self.portability_request_id)
      request.update_attribute(:status, PortabilityRequest::AVERBADO)
    end
  end

  def finish_portability
    if self.contract_type == Loan::PORT
      operator = Operator.find(self.operator_id)
      loan_id = self.children.first.id
      operator_request = PortabilityRequest.where(:buyer_id => operator.get_consignee.id, :status => PortabilityRequest::AVERBADO, :loan_id => loan_id).first
      operator_request.update_attribute(:status, PortabilityRequest::FINALIZADO)
      other_requests = PortabilityRequest.where('buyer_id != ? and status not in (?) and loan_id = ?', operator.get_consignee.id, [PortabilityRequest::RETIDO, PortabilityRequest::FINALIZADO, PortabilityRequest::CANCELADO], loan_id)
      other_requests.each do |request|
        request.update_attribute(:status, PortabilityRequest::CANCELADO)
      end
    end
    if self.operation_type == 'RETAIN'
      operator = Operator.find(self.operator_id)
      loan_id = self.children.first.id
      other_requests = PortabilityRequest.where('buyer_id != ? and status not in (?) and loan_id = ?', operator.get_consignee.id, [PortabilityRequest::RETIDO, PortabilityRequest::FINALIZADO, PortabilityRequest::CANCELADO], loan_id)
      other_requests.each do |request|
        request.update_attribute(:status, PortabilityRequest::CANCELADO)
      end
    end
  end
end

app/models/loan/as_approve_loan.rb
class Loan::AsApproveLoan < ActiveType::Record[Loan]

  attribute :observation, :text
  attribute :operator_id, :integer

  before_save :set_approved_status
  after_save :create_observation if :validate_observation

  validates :contract_number, :presence => true
  validates :interest_tax, :presence => true
  validates :cet, :presence => true
  validates :others, :presence => true

  def create_observation
    if !self.observation.blank?
      observation = LoanObservation.new
      observation.text = self.observation
      observation.operator_id = self.operator_id
      observation.loan = self
      observation.save!
    end
  end

  def set_approved_status
    self.status = Loan::APROVADO
  end

  def validate_observation
    self.observation.blank? ? false : true
  end

end

app/models/loan/as_liquidate_loan.rb
class Loan::AsLiquidateLoan < ActiveType::Record[Loan]

  attribute :observation, :string
  attribute :operator_id, :integer

  validates :observation, :presence => true

  before_save :set_status
  before_save :liquidate_installments
  after_save :create_observation

  def set_status
    self.status = Loan::LIQUIDADO
  end

  def liquidate_installments
    self.installments_paid = self.deadline
  end

  def create_observation
    observation = LoanObservation.new
    observation.text = self.observation
    observation.operator_id = operator_id
    observation.loan = self
    observation.save!
  end

end

app/models/loan/as_suspend_loan.rb
class Loan::AsSuspendLoan < ActiveType::Record[Loan]

  attribute :observation, :text
  attribute :operator_id, :integer

  validates :observation, :presence => true

  before_save :set_status
  after_save :create_observation

  def set_status
    self.status = Loan::SUSPENSO
  end

  def create_observation
    observation = LoanObservation.new
    observation.text = self.observation
    observation.operator_id = self.operator_id
    observation.loan = self
    observation.save!
  end
end

app/helpers/loan_helper.rb
module LoanHelper
end

app/views/loan/_form_portability.html.erb
<%= form_for @loan, :url => create_portability_path do |f| %>
    <div class="row">
      <div class="col-lg-12">
        <section class="panel">
          <header class="panel-heading">
            <h2 class="panel-title"><%= 'Empréstimos' %></h2>
          </header>
          <div class="panel-body">
                <%= render :partial => 'loan/loan_grid_for_portability_operation', :locals => {:f => f} %>
          </div>
        </section>
      </div>
    </div>
    <div class="row">
      <div class="col-lg-12">
        <section class="panel">
          <header class="panel-heading">
            <h2 class="panel-title"><%= 'Dados do empréstimo' %></h2>
          </header>
          <div class="panel-body">

            <%= f.hidden_field :origin_operation, :value => @operation %>
            <%= f.hidden_field :operation_type, :value => @operation_type %>
            <%= f.hidden_field :operator_id, :value => current_user.operator.id %>
            <%= f.hidden_field :consignee_id, :value => current_user.get_consignee.id%>
            <%= f.hidden_field :public_employee_id, :value => @employee.id%>
            <%= f.hidden_field :portability_request_id, :value => @portability_request_id %>

            <div class="row">
              <div class="col-sm-3">
                <div class="form-group">
                  <%= f.label :installment_value, class: 'control-label asterisk' %>
                  <%= f.text_field :installment_value, class: 'form-control money', :required => true, :readonly => f.object.persisted? %>
                  <%= "<span class='help-block-error'>#{@loan.errors[:installment_value].first}</span>".html_safe if @loan.errors[:installment_value].first %>
                </div>
              </div>
              <div class="col-sm-3">
                <div class="form-group">
                  <%= f.label :deadline, class: 'control-label asterisk' %>
                  <%= f.number_field :deadline, class: 'form-control', :required => true, :readonly => f.object.persisted? %>
                  <%= "<span class='help-block-error'>#{@loan.errors[:deadline].first}</span>".html_safe if @loan.errors[:deadline].first %>
                </div>
              </div>
              <div class="col-sm-3">
                <div class="form-group">
                  <%= f.label :others, class: 'control-label' %>
                  <%= f.text_field :others, class: 'form-control interest', :readonly => f.object.persisted?%>
                  <%= "<span class='help-block-error'>#{@loan.errors[:others].first}</span>".html_safe if @loan.errors[:others].first %>
                </div>
              </div>
            </div>

            <br>

            <div class="row">
              <div class="col-sm-3">
                <div class="form-group">
                  <%= f.label :liquid_value, class: 'control-label asterisk' %>
                  <%= f.text_field :liquid_value, class: 'form-control money', :required => true, :readonly => f.object.persisted? %>
                  <%= "<span class='help-block-error'>#{@loan.errors[:liquid_value].first}</span>".html_safe if @loan.errors[:liquid_value].first %>
                </div>
              </div>
              <div class="col-sm-3">
                <div class="form-group">
                  <%= f.label :interest_tax, class: 'control-label' %>
                  <%= f.text_field :interest_tax, class: 'form-control interest', :readonly => f.object.persisted?%>
                  <%= "<span class='help-block-error'>#{@loan.errors[:interest_tax].first}</span>".html_safe if @loan.errors[:interest_tax].first %>
                </div>
              </div>
              <div class="col-sm-3">
                <div class="form-group">

                </div>
              </div>
            </div>

            <br>

            <div class="row">
              <div class="col-sm-3">
                <div class="form-group">
                  <%= f.label :contract_value, class: 'control-label asterisk' %>
                  <%= f.text_field :contract_value, class: 'form-control money', :required => true, :readonly => f.object.persisted? %>
                  <%= "<span class='help-block-error'>#{@loan.errors[:contract_value].first}</span>".html_safe if @loan.errors[:contract_value].first %>
                </div>
              </div>
              <div class="col-sm-3">
                <div class="form-group">
                  <%= f.label :cet, class: 'control-label' %>
                  <%= f.text_field :cet, class: 'form-control interest', :readonly => f.object.persisted?%>
                  <%= "<span class='help-block-error'>#{@loan.errors[:cet].first}</span>".html_safe if @loan.errors[:cet].first %>
                </div>
              </div>
              <div class="col-sm-3">
                <div class="form-group">
                  <%= f.hidden_field :consignee_id_portability, :value => current_user.get_consignee.id %>
                </div>
              </div>
            </div>

          </div>
        </section>
      </div>
    </div>

    <div class="row">
      <div class="col-lg-3">
        <section class="panel">
          <div class="panel-body">
            <div class="form-group">
              <%= f.label :approval_password, class: 'control-label' %>
              <%= f.password_field :approval_password, class: 'form-control'%>
              <%= "<span class='help-block-error'>#{@loan.errors[:approval_password].first}</span>".html_safe if @loan.errors[:approval_password].first %>
            </div>
          </div>
        </section>
      </div>
    </div>

    <div class="actions">
      <%= f.submit :class => 'btn btn-primary' %>
      <%= link_to I18n.t('organ.back'), search_employee_path, class: 'btn btn-warning' %>
    </div>
<% end %>

app/views/loan/_manage_loan_grid.html.erb
<%= grid(@manage_loans_grid, show_filters: :when_filtered) do |g|

  g.blank_slate do
    content_tag :div, 'Nenhum empréstimo encontrado.', class: 'well'
  end

  g.column name: 'Contrato', attribute: 'contract_number', auto_reload: true do |loan|
    loan.contract_number
  end

  g.column name: 'Servidor', attribute: 'name', model: 'PublicEmployee', auto_reload: true do |loan|
    loan.public_employee.name if loan.public_employee
  end

  g.column name: 'Mátricula', attribute: 'registration', model: 'PublicEmployee', auto_reload: true do |loan|
    loan.public_employee.registration if loan.public_employee
  end

  g.column name: 'Parcela', attribute: 'installments_paid', auto_reload: true do |loan|
    loan.installments_paid
  end

  g.column name: 'Prazo', attribute: 'deadline', auto_reload: true do |loan|
    loan.deadline
  end

  g.column name: 'Data' do |loan|
    loan.created_at.strftime('%d/%m/%Y')
  end

  g.column name: 'Status', attribute: 'status', auto_reload: true do |loan|
    loan.status
  end

  g.column do |loan|

    buffer = link_to loan do
        '<i class="fa fa-lg fa-search" title="Exibir"></i>'.html_safe
    end

    if loan.status == Loan::AGUARDANDO_SERVIDOR
      if can? :edit, Loan
        buffer += '   '
        buffer += link_to edit_loan_path(loan) do
          '<i class="fa fa-lg fa-edit" title="Editar"></i>'.html_safe
        end
      end

    end

    if loan.status == Loan::AUTORIZADO_SERVIDOR || loan.status == Loan::AGUARDANDO_SERVIDOR
      if can? :cancel, Loan
        buffer += '   '
        buffer += link_to loan_cancel_path(loan) do
          '<i class="fa fa-lg fa-minus-circle" title="Cancelar Reserva"></i>'.html_safe
        end
      end
    end

    if loan.status == Loan::AUTORIZADO_SERVIDOR
      if can? :approve, Loan
        buffer += '   '
        buffer += link_to loan_approve_path(loan) do
          '<i class="fa fa-lg fa-check" title="Aprovar"></i>'.html_safe
        end
      end
      if can? :refuse, Loan
        buffer += '   '
        buffer += link_to refuse_loan_path(loan) do
          '<i class="fa fa-lg fa-remove" title="Recusar"></i>'.html_safe
        end
      end
    end


    if loan.status == Loan::EM_FOLHA
      if can? :suspended, Loan
        buffer += '   '
        buffer += link_to suspend_loan_path(loan) do
          '<i class="fa fa-lg fa-ban" title="Suspender"></i>'.html_safe
        end
      end
    end

    if loan.status == Loan::EM_FOLHA || loan.status == Loan::APROVADO
      if can? :liquidate, Loan
        buffer += '   '
        buffer += link_to liquidate_loan_path(loan) do
          '<i class="fa fa-lg fa-money" title="Liquidar"></i>'.html_safe
        end
      end
    end

    if loan.status == Loan::AGUARDANDO_PORTABLIDADE
      buffer += '   '
      buffer += link_to 'Portabilidade concluida', nil, method: :post, data: {confirm: "Você tem certeza que deseja informar que a portabilidade para o contrato \'#{loan.contract_number}\' foi concluida?"}
      buffer += '   '
      buffer += link_to 'Portabilidade não concluida', nil
    end

    raw buffer
  end

end -%>

app/views/loan/cancel.html.erb
<header class="page-header">
  <h2><%= 'Cancelar Reserva' %></h2>

  <div class="right-wrapper pull-right">
    <a class="sidebar-right-toggle" data-open="sidebar-right"><i class="fa fa-chevron-left"></i></a>
  </div>
</header>
<%= render :partial => 'loan/loan_information', :locals => {:loan => @loan} %>

<div class="row">
  <div class="col-lg-12">
    <%= form_for @loan, url: cancel_execute_loan_path, :html => {:class => 'form-horizontal form-bordered'} do |f| %>
        <section class="panel">
          <div class="panel-body">
            <%= f.hidden_field :operator_id, :value => current_user.operator.id %>
            <div class="form-group">
              <%= f.label :observation, class: 'col-md-3 control-label asterisk' %>
              <div class="col-md-6">
                <%= f.text_area :observation, class: 'form-control' %>
                <%= "<span class='help-block-error'>#{@loan.errors[:observation].first}</span>".html_safe if @loan.errors[:observation].first %>
              </div>
            </div>
            <div class="form-group">
              <%= f.label :approval_password, class: 'col-md-3 control-label asterisk' %>
              <div class="col-md-6">
                <%= f.password_field :approval_password, class: 'form-control' %>
                <%= "<span class='help-block-error'>#{@loan.errors[:approval_password].first}</span>".html_safe if @loan.errors[:approval_password].first %>
              </div>
            </div>
          </div>
        </section>
        <div class="actions">
          <%= f.submit 'Cancelar Reserva', :class => "btn btn-primary" %>
          <%= link_to I18n.t('reusable.back'), manage_loan_path, class: 'btn btn-warning' %>
        </div>
    <% end %>
  </div>
</div>